apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-config
  namespace: {{ .Release.Namespace }}
data:
  config.toml: |
    listen = "[::]:8080"
    allowed-hosts = []
    api-endpoint = ""

    soft-delete-caches = false
    require-proof-of-possession = true

    [database]
    heartbeatr = false

    [storage]
    type = "local"
    path = "/data"

    [chunking]
    nar-size-threshold = 65536
    min-size = 16384
    avg-size = 65536
    max-size = 262144

    [compression]
    type = "zstd"
    level = 8
